-- V1: 초기 스키마 (Flyway 도입 기준선)
--
-- 이 파일은 2026-07-29 시점의 **운영/개발 DB 실제 스키마**를 그대로 옮긴 것이다.
-- 그때까지는 Hibernate `ddl-auto: update` 가 엔티티에서 스키마를 만들어 왔고,
-- 이 마이그레이션 이후로는 스키마 변경이 전부 이 디렉터리의 SQL 파일로만 이뤄진다.
--
-- 작성 근거: dev/prod 양쪽 `pg_dump --schema-only` 를 떠서 비교했다. 제약조건·타입에 의미 있는
-- 차이가 없었고 **컬럼 추가 순서만** 달랐다(`update` 가 두 환경에서 서로 다른 시점에 컬럼을
-- 붙인 흔적). dev 덤프(2026-07-30) 기준 + 이후 엔티티 변경(FCM 알림 2테이블, 탈퇴·튜토리얼
-- 컬럼 — 2026-07-31)을 반영했으며 컬럼 순서는
-- 엔티티 기준으로 정리했다. 순서는 어떤 동작에도 영향이 없다(JPA 는 컬럼을 이름으로 참조).
--
-- ⚠️ prod 는 이 시점에 `categories.description` 과 `item_embeddings` 가 **없다**(AI 기능이
--    main 에 아직 머지되지 않았다). 그 격차는 V3 가 멱등하게 메운다 — Flyway 는 Hibernate 보다
--    먼저 실행되므로 `ddl-auto: validate` 가 컬럼 누락으로 기동을 실패시키기 전에 채워진다.
--
-- ⚠️ 이미 테이블이 있는 DB(dev/prod/팀원 로컬)에는 `spring.flyway.baseline-on-migrate=true`
--    때문에 이 파일이 **적용되지 않는다** — "V1 은 이미 적용된 상태"로 간주하고 V2 부터 실행된다.
--    따라서 이 파일이 실제로 실행되는 건 **빈 DB** 뿐이다(신규 팀원, CI, 로컬 초기화).
--
-- 📌 제약조건 이름은 **읽을 수 있는 이름으로 새로 정했다**(`pk_users`, `uk_users_provider`, …).
--    기존 DB 에는 Hibernate 가 붙인 이름이 남아 있다 — PK/CHECK 는 규칙적이지만
--    (`users_pkey`, `items_type_check`) UNIQUE/FK 10 개는 테이블·컬럼명을 해시한
--    `ukcbysvpk95086ud4n4g6mkspai` 꼴이라 읽을 수 없다.
--
--    그대로 두면 **환경마다 제약조건 이름이 갈린다**(기존 DB = Hibernate 이름, 새 DB = 이 파일의
--    이름). 이름은 애플리케이션 코드가 참조하지 않지만 **마이그레이션이 참조한다** — 예를 들어
--    enum 에 값을 추가할 때 CHECK 를 지우고 다시 만들어야 하는데, 그 SQL 이 한쪽 환경에서
--    반드시 실패한다. 그래서 **V2 가 기존 DB 의 이름 23 개를 이 파일의 이름으로 개명**해
--    모든 환경을 수렴시킨다(V2 는 새 DB 에서는 아무 것도 하지 않는다).

-- ===========================================================================
-- pgvector 익스텐션 (의미 기반 검색 + 우주 뷰 3D 좌표)
-- ===========================================================================
-- `vector(1536)` 타입을 쓰려면 먼저 있어야 한다. compose 가 postgres 를
-- `pgvector/pgvector:pg16` 으로 고정하므로 익스텐션 파일은 이미지에 들어 있다
-- — 옛 `postgres:16-alpine` 컨테이너로 돌리면 여기서 마이그레이션이 실패한다(의도된 fail-fast:
--   조용히 임베딩만 꺼지는 것보다 원인을 즉시 드러내는 게 낫다).
CREATE EXTENSION IF NOT EXISTS vector;

-- ===========================================================================
-- users
-- ===========================================================================
CREATE TABLE users (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at            timestamp(6) with time zone NOT NULL,
    updated_at            timestamp(6) with time zone NOT NULL,
    avatar_color          character varying(20)  NOT NULL,
    -- 회원 탈퇴(soft delete). NULL = 활성 회원.
    deleted_at            timestamp(6) with time zone,
    email                 character varying(255) NOT NULL,
    email_verified        boolean                NOT NULL,
    nickname              character varying(50)  NOT NULL,
    password_hash         character varying(255),
    -- 최초 이용 안내(튜토리얼) 완료 여부 — 개인/공유 워크스페이스 독립 관리.
    -- DEFAULT 는 엔티티의 columnDefinition 과 일치시킨 것(기존 행을 false 로 안전하게 채움).
    personal_tutorial_completed          boolean NOT NULL DEFAULT false,
    shared_workspace_tutorial_completed  boolean NOT NULL DEFAULT false,
    -- 개인 워크스페이스 id. 연관 매핑이 아니라 생 id 로 들고 있어 FK 가 없다(아래 주석 참고).
    personal_workspace_id bigint,
    profile_image_url     text,
    provider              character varying(20)  NOT NULL,
    provider_id           character varying(100),

    CONSTRAINT pk_users PRIMARY KEY (id),

    -- 소셜 로그인 중복 가입 방지. LOCAL 가입은 provider_id 가 NULL 이라 이 제약이 걸리지 않는다
    -- (Postgres 는 NULL 을 서로 다른 값으로 취급).
    CONSTRAINT uk_users_provider UNIQUE (provider, provider_id),

    -- CHECK 제약은 Hibernate 가 @Enumerated(STRING) 에서 자동 생성한 것을 옮긴 것이다.
    -- ⚠️ enum 에 값을 추가하면 이 목록도 마이그레이션으로 같이 늘려야 한다.
    --    `ddl-auto: update` 는 기존 CHECK 를 갱신하지 않아, 새 값을 저장하는 순간
    --    제약조건 위반으로 실패한다(기동은 정상이라 배포 시점에는 안 드러난다).
    CONSTRAINT ck_users_avatar_color CHECK (avatar_color IN (
        'RED', 'ORANGE', 'YELLOW', 'GREEN', 'BLUE', 'NAVY',
        'PURPLE', 'PINK', 'CRIMSON', 'BLACK', 'WHITE')),
    CONSTRAINT ck_users_provider CHECK (provider IN ('LOCAL', 'KAKAO', 'GOOGLE'))
);

-- ⚠️ email 에 UNIQUE 가 없다 — 현재 스키마를 그대로 옮긴 결과다.
--    가입 시 중복 검사를 애플리케이션에서만 하고 있어, 동시 요청이 겹치면 같은 이메일의
--    LOCAL 계정이 둘 생길 수 있다. 추가는 기존 중복 데이터 확인이 필요해 V1 에서는 하지 않았다.
--    → 백로그: `CREATE UNIQUE INDEX ... ON users(email) WHERE provider = 'LOCAL'` 검토

-- ===========================================================================
-- workspaces
-- ===========================================================================
CREATE TABLE workspaces (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    name       character varying(100) NOT NULL,
    type       character varying(20)  NOT NULL,
    created_by bigint                 NOT NULL,

    CONSTRAINT pk_workspaces PRIMARY KEY (id),
    CONSTRAINT fk_workspaces_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_workspaces_type CHECK (type IN ('PERSONAL', 'TEAM'))
);

-- ===========================================================================
-- workspace_members
-- ===========================================================================
CREATE TABLE workspace_members (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    joined_at    timestamp(6) with time zone NOT NULL,
    role         character varying(20) NOT NULL,
    user_id      bigint                NOT NULL,
    workspace_id bigint                NOT NULL,

    CONSTRAINT pk_workspace_members PRIMARY KEY (id),
    CONSTRAINT uk_workspace_members_ws_user UNIQUE (workspace_id, user_id),
    CONSTRAINT fk_workspace_members_user      FOREIGN KEY (user_id)      REFERENCES users (id),
    CONSTRAINT fk_workspace_members_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id),
    CONSTRAINT ck_workspace_members_role CHECK (role IN ('OWNER', 'MEMBER'))
);

-- ===========================================================================
-- workspace_invitations
-- ===========================================================================
CREATE TABLE workspace_invitations (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    code         character varying(64) NOT NULL,
    expires_at   timestamp(6) with time zone NOT NULL,
    created_by   bigint                NOT NULL,
    workspace_id bigint                NOT NULL,

    CONSTRAINT pk_workspace_invitations PRIMARY KEY (id),
    CONSTRAINT uk_workspace_invitations_code UNIQUE (code),
    CONSTRAINT fk_workspace_invitations_created_by FOREIGN KEY (created_by)   REFERENCES users (id),
    CONSTRAINT fk_workspace_invitations_workspace  FOREIGN KEY (workspace_id) REFERENCES workspaces (id)
);

-- ===========================================================================
-- items
-- ===========================================================================
-- ⚠️ workspace_id / created_by 에 FK 가 없다 — 엔티티가 연관 매핑(@ManyToOne) 대신 생 id
--    (`Long workspaceId`)를 들고 있어서 Hibernate 가 FK 를 만들지 않았다. 현재 스키마를
--    그대로 옮긴 것이고, 추가하려면 기존 고아 행 확인이 필요하다 → 백로그.
CREATE TABLE items (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at            timestamp(6) with time zone NOT NULL,
    updated_at            timestamp(6) with time zone NOT NULL,
    address               character varying(300),
    content               text,
    created_by            bigint                NOT NULL,
    -- 소프트 삭제(휴지통). NULL = 활성. 아래 부분 인덱스들이 이 컬럼을 조건으로 쓴다.
    deleted_at            timestamp(6) with time zone,
    favorite              boolean               NOT NULL,
    lat                   double precision,
    lng                   double precision,
    preview_description   text,
    preview_thumbnail_url text,
    s3key                 character varying(500),
    status                character varying(15) NOT NULL,
    summary               text,
    thumbnails3key        character varying(500),
    title                 character varying(500),
    type                  character varying(10) NOT NULL,
    url                   text,
    workspace_id          bigint                NOT NULL,

    CONSTRAINT pk_items PRIMARY KEY (id),
    CONSTRAINT ck_items_status CHECK (status IN ('PROCESSING', 'DONE', 'PARTIAL', 'FAILED')),
    CONSTRAINT ck_items_type   CHECK (type   IN ('URL', 'IMAGE', 'MEMO'))
);

-- 활성 아이템 조회의 기본 인덱스. 목록(ORDER BY created_at DESC LIMIT n)과 검색이 함께 쓴다.
--
-- deleted_at 을 인덱스 "컬럼"이 아니라 WHERE 조건으로 뺀 게 핵심이다. 컬럼으로 넣으면
-- btree 가 정렬 순서를 보장하지 못해 플래너가 Bitmap 스캔 + Sort 로 떨어지고, LIMIT 28 인데도
-- 워크스페이스의 활성 아이템을 전부 읽는다. 부분 인덱스로 두면 정렬 컬럼이
-- (workspace_id, created_at) 만 남아 Index Scan 으로 앞 28건만 읽는다
-- — 20만 건/대상 1만 건 기준 6.4ms → 0.19ms.
--
-- 검색은 관련도로 정렬해 created_at 순서를 못 쓰지만, 대상을 해당 워크스페이스의 활성
-- 아이템으로 좁혀준다 — 검색이 텍스트 인덱스 없이 성립하는 건 전적으로 이 인덱스 덕분이다.
-- 휴지통 조회(deleted_at IS NOT NULL)는 이 인덱스를 쓰지 못한다(저트래픽이라 감수).
CREATE INDEX idx_items_ws_active ON items (workspace_id, created_at DESC)
    WHERE deleted_at IS NULL;

-- 지도 조회(GET /items/geo, FR-032) 전용. 좌표가 있는 아이템은 워크스페이스 전체의 소수라
-- (링크·메모 대부분은 위치가 없다) 조건을 인덱스 WHERE 로 밀어넣으면 인덱스가 아주 작아진다.
-- 좌표를 별도 테이블로 분리하지 않고 items 컬럼으로 둘 수 있는 근거가 이 인덱스다.
-- 정렬 컬럼을 두지 않은 건 지도 조회에 ORDER BY 도 페이지네이션도 없기 때문(응답이 좌표 배열).
CREATE INDEX idx_items_ws_geo ON items (workspace_id)
    WHERE lat IS NOT NULL AND lng IS NOT NULL AND deleted_at IS NULL;

-- 📌 위 두 인덱스는 Flyway 도입 전까지 `ItemIndexInitializer`(ApplicationReadyEvent 에서
--    CREATE INDEX IF NOT EXISTS 실행)가 만들고 있었다. 부분 인덱스는 JPA 애노테이션으로
--    표현할 수 없어 애플리케이션 코드가 DDL 을 대신 실행한 것이다. 이제 스키마의 소유권이
--    이 파일로 넘어왔으니 그 클래스는 제거 대상이다(성능 근거는 위 주석으로 옮겨 왔다).
--    ⚠️ 그 클래스의 경고는 여기서도 유효하다: **items 에 GENERATED 컬럼을 추가하면 안 된다.**
--       `ddl-auto` 가 남아 있는 환경에서 content 의 타입 변경 ALTER 가 거부돼 기동이 실패한다.

-- ===========================================================================
-- categories
-- ===========================================================================
-- ⚠️ workspace_id 에 FK 없음 (items 와 같은 이유 — 생 id 매핑) → 백로그
CREATE TABLE categories (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at   timestamp(6) with time zone NOT NULL,
    updated_at   timestamp(6) with time zone NOT NULL,
    color        character varying(20),
    -- AI 분류 입력용 판단 기준 설명. nullable — 기본 카테고리는 CategoryDescriptionBackfill 이
    -- 기동 시 채우고, 사용자 카테고리는 생성 후 비동기로 생성된다. null 이면 이름으로 폴백.
    description  character varying(500),
    name         character varying(50) NOT NULL,
    workspace_id bigint                NOT NULL,

    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uk_categories_ws_name UNIQUE (workspace_id, name)
);

-- ===========================================================================
-- item_categories (아이템 ↔ 카테고리 N:M)
-- ===========================================================================
-- ⚠️ item_id / category_id 에 FK 없음 (생 id 매핑) → 백로그.
--    조인 테이블에 FK 가 없으면 아이템/카테고리를 지웠을 때 연결 행이 그대로 남는다.
CREATE TABLE item_categories (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    category_id bigint NOT NULL,
    item_id     bigint NOT NULL,

    CONSTRAINT pk_item_categories PRIMARY KEY (id),
    CONSTRAINT uk_item_categories_item_category UNIQUE (item_id, category_id)
);

-- ===========================================================================
-- notifications (인앱 알림함 — 아이템 처리 완료 시 생성)
-- ===========================================================================
-- ⚠️ user_id/item_id 에 FK 없음 — 엔티티가 생 id 를 쓰는 기존 패턴(items 등)과 동일. → 백로그
CREATE TABLE notifications (
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id    bigint                 NOT NULL,
    item_id    bigint                 NOT NULL,
    message    character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,

    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

-- ===========================================================================
-- notification_tokens (FCM 기기 토큰 — User:Token = 1:N)
-- ===========================================================================
CREATE TABLE notification_tokens (
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id     bigint                 NOT NULL,
    -- 토큰은 기기/브라우저 설치 단위로 유일 — 같은 토큰 재등록 시 소유자만 갱신된다(reassignTo)
    token       character varying(255) NOT NULL,
    device_info character varying(255),
    created_at  timestamp(6) with time zone NOT NULL,

    CONSTRAINT pk_notification_tokens PRIMARY KEY (id),
    CONSTRAINT uk_notification_tokens_token UNIQUE (token)
);

-- ===========================================================================
-- item_embeddings (의미 기반 검색 + 우주 뷰 3D 좌표)
-- ===========================================================================
-- JPA 엔티티가 **아니다** — `vector(1536)` 을 `ddl-auto` 아래 두면 Hibernate 가 매 기동마다
-- 타입 재검사 경로에 들어가고(items 의 GENERATED 컬럼 함정과 같은 계열), 접근 패턴이 전부
-- 단건 upsert / 워크스페이스 벌크 조회라 JPA 의 이점도 없다. 유사도 검색도 pgvector 연산자
-- (`<=>`)를 쓰는 네이티브 SQL 이다. 상세 근거는 ItemEmbeddingSchemaInitializer javadoc.
--
-- 📌 그 클래스가 기동 시 이 DDL 을 직접 실행하고 있었다(Flyway 가 없어서). 이제 소유권이
--    이 파일로 넘어왔으니 **제거 대상**이다 — 남겨 둬도 전부 IF NOT EXISTS 라 no-op 이지만,
--    남겨 두면 새 환경에서 Postgres 기본 제약조건 이름(`item_embeddings_pkey`)을 다시 만들어
--    이름 규칙이 또 갈린다. 제거는 백엔드 담당 판단이라 이 마이그레이션에 포함하지 않았다.
CREATE TABLE item_embeddings (
    -- item_id 가 PK — 아이템당 임베딩 하나. 영구 삭제 시 함께 지워지도록 FK CASCADE.
    -- (휴지통 soft delete 는 행을 남기고, 조회 쪽에서 items.deleted_at 으로 거른다)
    item_id         bigint NOT NULL,
    -- workspace_id 를 중복 보관하는 건 재계산·좌표 조회가 워크스페이스 단위 벌크라
    -- 매번 items 를 조인해 거를 필요를 줄이기 위해서다.
    workspace_id    bigint NOT NULL,
    embedding       vector(1536) NOT NULL,
    embedding_model character varying(100),
    input_hash      character varying(100),
    -- x/y/z 가 nullable 인 건 "임베딩은 저장됐지만 아직 좌표 재계산 전"인 순간이 있어서다.
    x               double precision,
    y               double precision,
    z               double precision,
    updated_at      timestamp with time zone NOT NULL DEFAULT now(),

    CONSTRAINT pk_item_embeddings PRIMARY KEY (item_id),
    CONSTRAINT fk_item_embeddings_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE
);

CREATE INDEX idx_item_embeddings_ws ON item_embeddings (workspace_id);
