-- ===========================================================================
-- workspace_member_activities
-- ===========================================================================
-- 멤버 활동 피드(가입/탈퇴/추방)의 표시용 이력 — WorkspaceMember(현재 멤버십)나
-- WorkspaceBan(재입장 금지 여부)과 별개로, "무슨 일이 언제 있었는지"만 나열한다.
CREATE TABLE workspace_member_activities (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    type         character varying(20)       NOT NULL,
    occurred_at  timestamp(6) with time zone NOT NULL,
    user_id      bigint                       NOT NULL,
    workspace_id bigint                       NOT NULL,

    CONSTRAINT pk_workspace_member_activities PRIMARY KEY (id),
    CONSTRAINT fk_workspace_member_activities_user      FOREIGN KEY (user_id)      REFERENCES users (id),
    CONSTRAINT fk_workspace_member_activities_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id),
    CONSTRAINT ck_workspace_member_activities_type CHECK (type IN ('JOINED', 'LEFT', 'KICKED'))
);

CREATE INDEX idx_workspace_member_activities_ws_occurred
    ON workspace_member_activities (workspace_id, occurred_at DESC);
