-- ===========================================================================
-- workspace_member_last_seens
-- ===========================================================================
-- 사용자가 워크스페이스의 멤버 활동 피드를 마지막으로 확인한 시각.
-- 행이 없으면 "한 번도 확인한 적 없음"을 뜻한다.
CREATE TABLE workspace_member_last_seens (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    last_seen_at timestamp(6) with time zone NOT NULL,
    user_id      bigint                       NOT NULL,
    workspace_id bigint                       NOT NULL,

    CONSTRAINT pk_workspace_member_last_seens PRIMARY KEY (id),
    CONSTRAINT uk_workspace_member_last_seens_ws_user UNIQUE (workspace_id, user_id),
    CONSTRAINT fk_workspace_member_last_seens_user      FOREIGN KEY (user_id)      REFERENCES users (id),
    CONSTRAINT fk_workspace_member_last_seens_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id)
);
