CREATE TABLE chat_channel_mappings (
    id           bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at   timestamp(6) with time zone NOT NULL,
    updated_at   timestamp(6) with time zone NOT NULL,
    platform     character varying(20)  NOT NULL,
    channel_id   character varying(100) NOT NULL,
    workspace_id bigint                 NOT NULL,
    created_by   bigint                 NOT NULL,

    CONSTRAINT pk_chat_channel_mappings PRIMARY KEY (id),
    CONSTRAINT uk_chat_channel_mappings_platform_channel UNIQUE (platform, channel_id),
    CONSTRAINT fk_chat_channel_mappings_workspace
        FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_channel_mappings_creator
        FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_chat_channel_mappings_platform
        CHECK (platform IN ('DISCORD', 'MATTERMOST'))
);

CREATE INDEX idx_chat_channel_mappings_creator
    ON chat_channel_mappings (created_by);
