CREATE TABLE chat_account_connections (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at           timestamp(6) with time zone NOT NULL,
    updated_at           timestamp(6) with time zone NOT NULL,
    platform             character varying(20)  NOT NULL,
    external_user_id     character varying(100) NOT NULL,
    user_id              bigint                 NOT NULL,
    default_workspace_id bigint,

    CONSTRAINT pk_chat_account_connections PRIMARY KEY (id),
    CONSTRAINT uk_chat_account_connections_platform_user UNIQUE (platform, external_user_id),
    CONSTRAINT fk_chat_account_connections_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_chat_account_connections_workspace
        FOREIGN KEY (default_workspace_id) REFERENCES workspaces (id),
    CONSTRAINT ck_chat_account_connections_platform
        CHECK (platform IN ('DISCORD', 'MATTERMOST'))
);

CREATE INDEX idx_chat_account_connections_user
    ON chat_account_connections (user_id);
